import 'package:flutter/material.dart';
import 'package:flutterapp/slaskieapp/generatedankietylistawidget/generated/GeneratedRectangle1Widget13.dart';
import 'package:flutterapp/slaskieapp/generatedankietylistawidget/generated/GeneratedGuidesWidget8.dart';
import 'package:flutterapp/slaskieapp/generatedankietylistawidget/generated/GeneratedGuidesWidget11.dart';
import 'package:flutterapp/slaskieapp/generatedankietylistawidget/generated/GeneratedAnkietyWidget4.dart';
import 'package:flutterapp/slaskieapp/generatedankietylistawidget/generated/GeneratedGuidesWidget9.dart';
import 'package:flutterapp/slaskieapp/generatedankietylistawidget/generated/GeneratedGuidesWidget7.dart';
import 'package:flutterapp/slaskieapp/generatedankietylistawidget/generated/GeneratedGuidesWidget6.dart';
import 'package:flutterapp/slaskieapp/generatedankietylistawidget/generated/GeneratedBrowserBariOSChromeWidget5.dart';
import 'package:flutterapp/slaskieapp/generatedankietylistawidget/generated/GeneratedFrame8Widget2.dart';
import 'package:flutterapp/slaskieapp/generatedankietylistawidget/generated/GeneratedBackArrowWidget3.dart';
import 'package:flutterapp/slaskieapp/generatedankietylistawidget/generated/GeneratedGuidesWidget10.dart';
import 'package:flutterapp/slaskieapp/generatedankietylistawidget/generated/GeneratedDolnabelkamenuWidget2.dart';
import 'package:flutterapp/slaskieapp/generatedankietylistawidget/generated/GeneratedBytesizesettingsWidget14.dart';
import 'package:flutterapp/slaskieapp/generatedankietylistawidget/generated/GeneratedFrame9Widget2.dart';

/* Frame Ankiety lista
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAnkietylistaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 860.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 7.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 16.0,
                child: GeneratedBrowserBariOSChromeWidget5(),
              ),
              Positioned(
                left: 13.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 39.0,
                child: GeneratedFrame8Widget2(),
              ),
              Positioned(
                left: 13.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 39.0,
                child: GeneratedFrame9Widget2(),
              ),
              Positioned(
                left: 360.0,
                top: 1214.0,
                right: null,
                bottom: null,
                width: 359.9999694824219,
                height: 189.00003051757812,
                child: GeneratedRectangle1Widget13(),
              ),
              Positioned(
                left: 14.0,
                top: 49.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedBackArrowWidget3(),
              ),
              Positioned(
                left: 322.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBytesizesettingsWidget14(),
              ),
              Positioned(
                left: 140.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 33.0,
                child: GeneratedAnkietyWidget4(),
              ),
              Positioned(
                left: 12.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 192.0,
                child: GeneratedGuidesWidget6(),
              ),
              Positioned(
                left: 186.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 192.0,
                child: GeneratedGuidesWidget7(),
              ),
              Positioned(
                left: 12.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 192.0,
                child: GeneratedGuidesWidget8(),
              ),
              Positioned(
                left: 186.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 192.0,
                child: GeneratedGuidesWidget9(),
              ),
              Positioned(
                left: 11.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 192.0,
                child: GeneratedGuidesWidget10(),
              ),
              Positioned(
                left: 185.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 192.0,
                child: GeneratedGuidesWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: 725.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 77.0,
                child: GeneratedDolnabelkamenuWidget2(),
              )
            ]),
      ),
    ));
  }
}
