import 'package:flutter/material.dart';

/* UndefinedNode Guides
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGuidesWidget26 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
