import 'package:flutter/material.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedEllipse1Widget3.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedGuidesWidget1.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedAnkietyWidget2.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedGuidesWidget4.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedEllipse3Widget2.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedBrowserBariOSChromeWidget2.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedBytesizesettingsWidget4.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedWParkulskimpowstaniedrugaliniaKoleiLinowejElkaWidget1.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedFrame9Widget1.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedMaterialsymbolshomeWidget.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedWydarzeniaWidget2.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedFrame10Widget1.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedGuidesWidget2.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedComponent2Widget2.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedRectangle1Widget7.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedRectangle6Widget3.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedRectangle10Widget1.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedFrame8Widget1.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedComponent3Widget2.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedEllipse2Widget12.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedLogoslaskiebialecmyk1Widget.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedFrame11Widget1.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedUnsplashw3dclmLbh3EWidget1.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedGuidesWidget3.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenkontrastowawidget/generated/GeneratedPopularItineraryWidget2.dart';

/* Frame Home Screen Kontrastowa
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeScreenKontrastowaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1403.0000305175781,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 1171.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 668.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 546.0,
                              child: GeneratedRectangle10Widget1(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 938.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 192.0,
                              child: GeneratedGuidesWidget1(),
                            ),
                            Positioned(
                              left: 187.0,
                              top: 938.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 192.0,
                              child: GeneratedGuidesWidget2(),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 10.0,
                              right: null,
                              bottom: null,
                              width: 346.0,
                              height: 16.0,
                              child: GeneratedBrowserBariOSChromeWidget2(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 88.0,
                              right: null,
                              bottom: null,
                              width: 333.0,
                              height: 39.0,
                              child: GeneratedFrame8Widget1(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 143.0,
                              right: null,
                              bottom: null,
                              width: 142.0,
                              height: 31.0,
                              child: GeneratedFrame9Widget1(),
                            ),
                            Positioned(
                              left: 160.0,
                              top: 143.0,
                              right: null,
                              bottom: null,
                              width: 123.0,
                              height: 31.0,
                              child: GeneratedFrame10Widget1(),
                            ),
                            Positioned(
                              left: 176.0,
                              top: 365.0,
                              right: null,
                              bottom: null,
                              width: 8.0,
                              height: 8.0,
                              child: GeneratedEllipse1Widget3(),
                            ),
                            Positioned(
                              left: 160.0,
                              top: 365.0,
                              right: null,
                              bottom: null,
                              width: 8.0,
                              height: 8.0,
                              child: GeneratedEllipse2Widget12(),
                            ),
                            Positioned(
                              left: 192.0,
                              top: 365.0,
                              right: null,
                              bottom: null,
                              width: 8.0,
                              height: 8.0,
                              child: GeneratedEllipse3Widget2(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 191.0,
                              right: null,
                              bottom: null,
                              width: 334.0,
                              height: 167.0,
                              child: GeneratedUnsplashw3dclmLbh3EWidget1(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 298.0,
                              right: null,
                              bottom: null,
                              width: 334.0,
                              height: 60.0,
                              child: GeneratedRectangle6Widget3(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 308.0,
                              right: null,
                              bottom: null,
                              width: 314.0,
                              height: 38.0,
                              child:
                                  GeneratedWParkulskimpowstaniedrugaliniaKoleiLinowejElkaWidget1(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 394.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 28.0,
                              child: GeneratedWydarzeniaWidget2(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 684.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 30.0,
                              child: GeneratedAnkietyWidget2(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 430.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 214.0,
                              child: GeneratedPopularItineraryWidget2(),
                            ),
                            Positioned(
                              left: 171.0,
                              top: 430.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 214.0,
                              child: GeneratedComponent2Widget2(),
                            ),
                            Positioned(
                              left: 329.0,
                              top: 430.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 214.0,
                              child: GeneratedComponent3Widget2(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 728.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 192.0,
                              child: GeneratedGuidesWidget3(),
                            ),
                            Positioned(
                              left: 187.0,
                              top: 728.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 192.0,
                              child: GeneratedGuidesWidget4(),
                            ),
                            Positioned(
                              left: 360.0,
                              top: 1214.0,
                              right: null,
                              bottom: null,
                              width: 359.9999694824219,
                              height: 189.00003051757812,
                              child: GeneratedRectangle1Widget7(),
                            ),
                            Positioned(
                              left: 288.0,
                              top: 143.0,
                              right: null,
                              bottom: null,
                              width: 142.0,
                              height: 31.0,
                              child: GeneratedFrame11Widget1(),
                            ),
                            Positioned(
                              left: 323.0,
                              top: 47.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedBytesizesettingsWidget4(),
                            ),
                            Positioned(
                              left: 100.0,
                              top: 34.0,
                              right: null,
                              bottom: null,
                              width: 159.0,
                              height: 50.0,
                              child: GeneratedLogoslaskiebialecmyk1Widget(),
                            ),
                            Positioned(
                              left: 251.0,
                              top: 234.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedMaterialsymbolshomeWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
