import 'package:flutter/material.dart';
import 'package:flutterapp/slaskieapp/generatedframe1widget10/generated/GeneratedRectangle1Widget34.dart';
import 'package:flutterapp/slaskieapp/generatedframe1widget10/generated/GeneratedRectangle2Widget25.dart';

/* Frame Frame 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame1Widget10 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1447.0,
        height: 818.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 35.0,
                top: 37.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 87.0,
                child: GeneratedRectangle1Widget34(),
              ),
              Positioned(
                left: 144.0,
                top: 37.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 87.0,
                child: GeneratedRectangle2Widget25(),
              )
            ]),
      ),
    ));
  }
}
