import 'package:flutter/material.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnoszczegywidget/generated/GeneratedBackArrowWidget4.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnoszczegywidget/generated/Generated27padziernika2022Widget.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnoszczegywidget/generated/GeneratedBytesizesettingsWidget18.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnoszczegywidget/generated/GeneratedWuroczystympodpisaniuumowydotyczcejrealizacjiliniibiegn.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnoszczegywidget/generated/GeneratedDolnabelkamenuWidget3.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnoszczegywidget/generated/GeneratedGuidesWidget12.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnoszczegywidget/generated/GeneratedBrowserBariOSChromeWidget6.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnoszczegywidget/generated/GeneratedClaritydatelineWidget.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnoszczegywidget/generated/GeneratedReviewWidget4.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnoszczegywidget/generated/GeneratedUnsplashw3dclmLbh3EWidget3.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnoszczegywidget/generated/GeneratedZrzutekranu2022123o17243Widget.dart';

/* Frame Aktualność - szczegóły
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAktualnoszczegyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1340.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 1340.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 10.0,
                              right: null,
                              bottom: null,
                              width: 346.0,
                              height: 16.0,
                              child: GeneratedBrowserBariOSChromeWidget6(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 93.0,
                              right: null,
                              bottom: null,
                              width: 361.0,
                              height: 219.0,
                              child: GeneratedUnsplashw3dclmLbh3EWidget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 312.0,
                              right: null,
                              bottom: null,
                              width: 362.0,
                              height: 1028.0,
                              child: GeneratedReviewWidget4(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 359.0,
                              right: null,
                              bottom: null,
                              width: 342.0,
                              height: 957.0,
                              child:
                                  GeneratedWuroczystympodpisaniuumowydotyczcejrealizacjiliniibiegn(),
                            ),
                            Positioned(
                              left: 14.0,
                              top: 49.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedBackArrowWidget4(),
                            ),
                            Positioned(
                              left: 322.0,
                              top: 52.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedBytesizesettingsWidget18(),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 327.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedClaritydatelineWidget(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 329.0,
                              right: null,
                              bottom: null,
                              width: 133.0,
                              height: 18.0,
                              child: Generated27padziernika2022Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 254.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 58.0,
                              child: GeneratedGuidesWidget12(),
                            ),
                            Positioned(
                              left: 139.0,
                              top: 43.0,
                              right: null,
                              bottom: null,
                              width: 85.17073059082031,
                              height: 36.0,
                              child: GeneratedZrzutekranu2022123o17243Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 725.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 77.0,
                              child: GeneratedDolnabelkamenuWidget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
