import 'package:flutter/material.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget/generated/GeneratedGroup20Widget.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget/generated/GeneratedGroup35Widget.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget/generated/GeneratedGroup25Widget.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget/generated/GeneratedNotificationWidget.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget/generated/GeneratedSearchWidget.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget/generated/GeneratedGroup22Widget.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget/generated/GeneratedEllipse4Widget.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget/generated/GeneratedGroup41Widget.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget/generated/GeneratedNativeGuideWidget2.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget/generated/GeneratedGroup24Widget.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget/generated/GeneratedGroup21Widget.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget/generated/GeneratedCitiesselectionWidget.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget/generated/GeneratedGroup23Widget.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget/generated/GeneratedGroup14Widget.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget/generated/GeneratedRecommendedGuidesWidget.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget/generated/GeneratedEllipse5Widget.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget/generated/GeneratedRecommendedItinerariesWidget.dart';

/* Frame Home Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 33.0,
                top: 79.0,
                right: null,
                bottom: null,
                width: 347.0,
                height: 67.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 33.0,
                top: 27.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 19.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 128.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 55.0,
                child: GeneratedEllipse3Widget(),
              ),
              Positioned(
                left: 226.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 55.0,
                child: GeneratedEllipse4Widget(),
              ),
              Positioned(
                left: 324.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 55.0,
                child: GeneratedEllipse5Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 55.0,
                child: GeneratedGroup35Widget(),
              ),
              Positioned(
                left: 134.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 42.30057144165039,
                child: GeneratedGroup3Widget(),
              ),
              Positioned(
                left: 232.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 42.30057144165039,
                child: GeneratedGroup14Widget(),
              ),
              Positioned(
                left: 330.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 42.30057144165039,
                child: GeneratedGroup6Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 149.0,
                child: GeneratedGroup20Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 539.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 149.0,
                child: GeneratedGroup23Widget(),
              ),
              Positioned(
                left: 192.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 149.0,
                child: GeneratedGroup21Widget(),
              ),
              Positioned(
                left: 192.0,
                top: 539.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 149.0,
                child: GeneratedGroup24Widget(),
              ),
              Positioned(
                left: 351.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 149.0,
                child: GeneratedGroup22Widget(),
              ),
              Positioned(
                left: 351.0,
                top: 539.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 149.0,
                child: GeneratedGroup25Widget(),
              ),
              Positioned(
                left: 334.0,
                top: 22.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 28.0,
                child: GeneratedNotificationWidget(),
              ),
              Positioned(
                left: 145.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 29.0,
                child: GeneratedNativeGuideWidget2(),
              ),
              Positioned(
                left: 52.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 29.0,
                child: GeneratedSearchWidget(),
              ),
              Positioned(
                left: 35.0,
                top: 162.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 26.0,
                child: GeneratedCitiesselectionWidget(),
              ),
              Positioned(
                left: 35.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 214.0,
                height: 26.0,
                child: GeneratedRecommendedGuidesWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 498.0,
                right: null,
                bottom: null,
                width: 241.0,
                height: 26.0,
                child: GeneratedRecommendedItinerariesWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 744.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 68.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 759.0,
                right: null,
                bottom: null,
                width: 342.69000244140625,
                height: 38.0,
                child: GeneratedGroup41Widget(),
              )
            ]),
      ),
    ));
  }
}
