import 'package:flutter/material.dart';
import 'package:flutterapp/slaskieapp/generatedsplashscreenwidget/generated/GeneratedSloganHereWidget.dart';
import 'package:flutterapp/slaskieapp/generatedsplashscreenwidget/generated/GeneratedGetstartedWidget.dart';
import 'package:flutterapp/slaskieapp/generatedsplashscreenwidget/generated/GeneratedNativeGuideWidget1.dart';
import 'package:flutterapp/slaskieapp/generatedsplashscreenwidget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/slaskieapp/generatedsplashscreenwidget/generated/GeneratedRectangle5Widget1.dart';

/* Frame Splash Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 487.0,
                child: GeneratedGroup7Widget(),
              ),
              Positioned(
                left: 46.0,
                top: 626.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 24.0,
                child: GeneratedSloganHereWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 726.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 50.0,
                child: GeneratedRectangle5Widget1(),
              ),
              Positioned(
                left: 162.0,
                top: 743.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 20.0,
                child: GeneratedGetstartedWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 592.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 31.0,
                child: GeneratedNativeGuideWidget1(),
              )
            ]),
      ),
    ));
  }
}
