import 'package:flutter/material.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedRectangle10Widget2.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedFrame9Widget4.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedDolnabelkamenuWidget8.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedGuidesWidget25.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedUnsplashw3dclmLbh3EWidget5.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedEllipse2Widget13.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedAnkietyWidget6.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedFrame8Widget6.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedRectangle6Widget4.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedPopularItineraryWidget5.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedBytesizesettingsWidget30.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedFrame10Widget4.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedWydarzeniaWidget6.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedGuidesWidget22.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedBrowserBariOSChromeWidget11.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedComponent3Widget5.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedZrzutekranu2022123o17241Widget1.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedGuidesWidget23.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedGuidesWidget24.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedRectangle1Widget28.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedFrame11Widget4.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedEllipse3Widget3.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedComponent2Widget5.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedWParkulskimpowstaniedrugaliniaKoleiLinowejElkaWidget2.dart';
import 'package:flutterapp/slaskieapp/generatedhomescreenwidget1/generated/GeneratedEllipse1Widget19.dart';

/* Frame Home Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeScreenWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1403.0000305175781,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 1240.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 668.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 572.0,
                              child: GeneratedRectangle10Widget2(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 938.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 192.0,
                              child: GeneratedGuidesWidget22(),
                            ),
                            Positioned(
                              left: 187.0,
                              top: 938.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 192.0,
                              child: GeneratedGuidesWidget23(),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 9.0,
                              right: null,
                              bottom: null,
                              width: 346.0,
                              height: 16.0,
                              child: GeneratedBrowserBariOSChromeWidget11(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 88.0,
                              right: null,
                              bottom: null,
                              width: 333.0,
                              height: 39.0,
                              child: GeneratedFrame8Widget6(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 143.0,
                              right: null,
                              bottom: null,
                              width: 142.0,
                              height: 31.0,
                              child: GeneratedFrame9Widget4(),
                            ),
                            Positioned(
                              left: 160.0,
                              top: 143.0,
                              right: null,
                              bottom: null,
                              width: 123.0,
                              height: 31.0,
                              child: GeneratedFrame10Widget4(),
                            ),
                            Positioned(
                              left: 176.0,
                              top: 365.0,
                              right: null,
                              bottom: null,
                              width: 8.0,
                              height: 8.0,
                              child: GeneratedEllipse1Widget19(),
                            ),
                            Positioned(
                              left: 160.0,
                              top: 365.0,
                              right: null,
                              bottom: null,
                              width: 8.0,
                              height: 8.0,
                              child: GeneratedEllipse2Widget13(),
                            ),
                            Positioned(
                              left: 192.0,
                              top: 365.0,
                              right: null,
                              bottom: null,
                              width: 8.0,
                              height: 8.0,
                              child: GeneratedEllipse3Widget3(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 191.0,
                              right: null,
                              bottom: null,
                              width: 334.0,
                              height: 167.0,
                              child: GeneratedUnsplashw3dclmLbh3EWidget5(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 298.0,
                              right: null,
                              bottom: null,
                              width: 334.0,
                              height: 60.0,
                              child: GeneratedRectangle6Widget4(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 308.0,
                              right: null,
                              bottom: null,
                              width: 314.0,
                              height: 38.0,
                              child:
                                  GeneratedWParkulskimpowstaniedrugaliniaKoleiLinowejElkaWidget2(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 394.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 28.0,
                              child: GeneratedWydarzeniaWidget6(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 684.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 30.0,
                              child: GeneratedAnkietyWidget6(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 430.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 214.0,
                              child: GeneratedPopularItineraryWidget5(),
                            ),
                            Positioned(
                              left: 171.0,
                              top: 430.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 214.0,
                              child: GeneratedComponent2Widget5(),
                            ),
                            Positioned(
                              left: 329.0,
                              top: 430.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 214.0,
                              child: GeneratedComponent3Widget5(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 728.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 192.0,
                              child: GeneratedGuidesWidget24(),
                            ),
                            Positioned(
                              left: 187.0,
                              top: 728.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 192.0,
                              child: GeneratedGuidesWidget25(),
                            ),
                            Positioned(
                              left: 360.0,
                              top: 1214.0,
                              right: null,
                              bottom: null,
                              width: 359.9999694824219,
                              height: 189.00003051757812,
                              child: GeneratedRectangle1Widget28(),
                            ),
                            Positioned(
                              left: 288.0,
                              top: 143.0,
                              right: null,
                              bottom: null,
                              width: 142.0,
                              height: 31.0,
                              child: GeneratedFrame11Widget4(),
                            ),
                            Positioned(
                              left: 322.0,
                              top: 52.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedBytesizesettingsWidget30(),
                            ),
                            Positioned(
                              left: 139.0,
                              top: 43.0,
                              right: null,
                              bottom: null,
                              width: 85.17073059082031,
                              height: 36.0,
                              child: GeneratedZrzutekranu2022123o17241Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 725.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 77.0,
                              child: GeneratedDolnabelkamenuWidget8(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
