import 'package:flutter/material.dart';
import 'package:flutterapp/slaskieapp/generatedsignupscreenwidget/generated/GeneratedSignUpWidget.dart';
import 'package:flutterapp/slaskieapp/generatedsignupscreenwidget/generated/GeneratedLastnameWidget.dart';
import 'package:flutterapp/slaskieapp/generatedsignupscreenwidget/generated/GeneratedCreatNewAccountWidget.dart';
import 'package:flutterapp/slaskieapp/generatedsignupscreenwidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/slaskieapp/generatedsignupscreenwidget/generated/GeneratedEmailWidget1.dart';
import 'package:flutterapp/slaskieapp/generatedsignupscreenwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/slaskieapp/generatedsignupscreenwidget/generated/GeneratedFirstnameWidget.dart';
import 'package:flutterapp/slaskieapp/generatedsignupscreenwidget/generated/GeneratedAlreadyRegisteredLoginWidget.dart';
import 'package:flutterapp/slaskieapp/generatedsignupscreenwidget/generated/GeneratedRectangle3Widget1.dart';
import 'package:flutterapp/slaskieapp/generatedsignupscreenwidget/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/slaskieapp/generatedsignupscreenwidget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/slaskieapp/generatedsignupscreenwidget/generated/GeneratedPasswordWidget1.dart';

/* Frame Signup Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignupScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 108.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 187.0,
                height: 26.0,
                child: GeneratedCreatNewAccountWidget(),
              ),
              Positioned(
                left: 47.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 55.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 47.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 55.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: 47.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 55.0,
                child: GeneratedRectangle3Widget1(),
              ),
              Positioned(
                left: 47.0,
                top: 446.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 55.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 47.0,
                top: 578.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 55.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 73.0,
                top: 206.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 20.0,
                child: GeneratedFirstnameWidget(),
              ),
              Positioned(
                left: 73.0,
                top: 287.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 20.0,
                child: GeneratedLastnameWidget(),
              ),
              Positioned(
                left: 74.0,
                top: 376.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 23.0,
                child: GeneratedEmailWidget1(),
              ),
              Positioned(
                left: 74.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 23.0,
                child: GeneratedPasswordWidget1(),
              ),
              Positioned(
                left: 173.0,
                top: 597.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 21.0,
                child: GeneratedSignUpWidget(),
              ),
              Positioned(
                left: 95.0,
                top: 662.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 20.0,
                child: GeneratedAlreadyRegisteredLoginWidget(),
              )
            ]),
      ),
    ));
  }
}
