import 'package:flutter/material.dart';
import 'package:flutterapp/slaskieapp/generatedloginscreenwidget/generated/GeneratedGroup48Widget.dart';
import 'package:flutterapp/slaskieapp/generatedloginscreenwidget/generated/GeneratedGroup47Widget.dart';
import 'package:flutterapp/slaskieapp/generatedloginscreenwidget/generated/GeneratedGroup45Widget.dart';
import 'package:flutterapp/slaskieapp/generatedloginscreenwidget/generated/GeneratedOrloginwithWidget.dart';
import 'package:flutterapp/slaskieapp/generatedloginscreenwidget/generated/GeneratedDonthaveanaccountsignupWidget.dart';
import 'package:flutterapp/slaskieapp/generatedloginscreenwidget/generated/GeneratedLogintoyourAccountWidget.dart';
import 'package:flutterapp/slaskieapp/generatedloginscreenwidget/generated/GeneratedGroup49Widget.dart';
import 'package:flutterapp/slaskieapp/generatedloginscreenwidget/generated/GeneratedNativeGuideWidget.dart';
import 'package:flutterapp/slaskieapp/generatedloginscreenwidget/generated/GeneratedGroup50Widget.dart';

/* Frame Login Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 45.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 31.0,
                child: GeneratedNativeGuideWidget(),
              ),
              Positioned(
                left: 96.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 224.0,
                height: 24.0,
                child: GeneratedLogintoyourAccountWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 50.0,
                child: GeneratedGroup47Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 324.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 50.0,
                child: GeneratedGroup48Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 396.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 20.0,
                child: GeneratedGroup50Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 50.0,
                child: GeneratedGroup49Widget(),
              ),
              Positioned(
                left: 86.0,
                top: 610.0,
                right: null,
                bottom: null,
                width: 243.0,
                height: 18.0,
                child: GeneratedDonthaveanaccountsignupWidget(),
              ),
              Positioned(
                left: 170.0,
                top: 678.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 15.0,
                child: GeneratedOrloginwithWidget(),
              ),
              Positioned(
                left: 118.0,
                top: 738.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 32.727272033691406,
                child: GeneratedGroup45Widget(),
              )
            ]),
      ),
    ));
  }
}
