import 'package:flutter/material.dart';

/* UndefinedNode Review
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedReviewWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
