import 'package:flutter/material.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzenialistawidget/generated/Generated16wynikwWidget2.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzenialistawidget/generated/GeneratedFrame8Widget5.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzenialistawidget/generated/GeneratedPopularItineraryWidget4.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzenialistawidget/generated/GeneratedBytesizesettingsWidget26.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzenialistawidget/generated/GeneratedBrowserBariOSChromeWidget10.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzenialistawidget/generated/GeneratedComponent3Widget4.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzenialistawidget/generated/GeneratedComponent5Widget.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzenialistawidget/generated/GeneratedFrame12Widget3.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzenialistawidget/generated/GeneratedWydarzeniaWidget5.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzenialistawidget/generated/GeneratedDolnabelkamenuWidget7.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzenialistawidget/generated/GeneratedComponent6Widget.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzenialistawidget/generated/GeneratedComponent4Widget2.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzenialistawidget/generated/GeneratedBackArrowWidget8.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzenialistawidget/generated/GeneratedRectangle1Widget25.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzenialistawidget/generated/GeneratedComponent2Widget4.dart';

/* Frame Wydarzenia lista
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWydarzenialistaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1403.0000305175781,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 975.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 10.0,
                              right: null,
                              bottom: null,
                              width: 346.0,
                              height: 16.0,
                              child: GeneratedBrowserBariOSChromeWidget10(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 88.0,
                              right: null,
                              bottom: null,
                              width: 333.0,
                              height: 39.0,
                              child: GeneratedFrame8Widget5(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 184.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 214.0,
                              child: GeneratedPopularItineraryWidget4(),
                            ),
                            Positioned(
                              left: 187.0,
                              top: 184.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 214.0,
                              child: GeneratedComponent2Widget4(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 426.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 214.0,
                              child: GeneratedComponent3Widget4(),
                            ),
                            Positioned(
                              left: 187.0,
                              top: 426.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 214.0,
                              child: GeneratedComponent4Widget2(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 668.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 214.0,
                              child: GeneratedComponent5Widget(),
                            ),
                            Positioned(
                              left: 187.0,
                              top: 668.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 214.0,
                              child: GeneratedComponent6Widget(),
                            ),
                            Positioned(
                              left: 360.0,
                              top: 1214.0,
                              right: null,
                              bottom: null,
                              width: 359.9999694824219,
                              height: 189.00003051757812,
                              child: GeneratedRectangle1Widget25(),
                            ),
                            Positioned(
                              left: 14.0,
                              top: 49.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedBackArrowWidget8(),
                            ),
                            Positioned(
                              left: 322.0,
                              top: 52.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedBytesizesettingsWidget26(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 145.0,
                              right: null,
                              bottom: null,
                              width: 85.0,
                              height: 22.0,
                              child: Generated16wynikwWidget2(),
                            ),
                            Positioned(
                              left: 116.0,
                              top: 50.0,
                              right: null,
                              bottom: null,
                              width: 132.0,
                              height: 33.0,
                              child: GeneratedWydarzeniaWidget5(),
                            ),
                            Positioned(
                              left: 134.0,
                              top: 139.0,
                              right: null,
                              bottom: null,
                              width: 207.0,
                              height: 31.0,
                              child: GeneratedFrame12Widget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 725.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 77.0,
                              child: GeneratedDolnabelkamenuWidget7(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
