import 'package:flutter/material.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedBiletnormalny45zBiletulgowy32zWidget.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedMaterialsymbolssquareroundedWidget4.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedWykonawcyWidget.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedMaterialsymbolssquareroundedWidget5.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedBrowserBariOSChromeWidget8.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedRomanWidaszekklarnetWidget.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedYaroslavShemetdyrygentWidget1.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedMaterialsymbolssquareroundedWidget1.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedYaroslavShemetdyrygentWidget.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedMaterialsymbolssquareroundedWidget2.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedZrzutekranu2022123o17242Widget.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedMaterialsymbolssquareroundedWidget.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/Generated2grudnia20221900Widget.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedMarcelChyrzyskiUkiyoeNo5Koncertnaklarnetiorkiestrsymfon.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedReviewWidget5.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedReviewWidget6.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedFrame40Widget8.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedHectorBerliozSymfoniafantastycznacmollop14Widget.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedSalaKoncertowaFilharmonialskaWidget.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedProgramWidget.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedOrkiestraSymfonicznaFilharmoniilskiejWidget.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedMaterialsymbolslocationonoutlineWidget.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedGuidesWidget21.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/Generated2grudniaOrkiestraSymfonicznaFilharmoniilskiejzaprosinan.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedUnsplashw3dclmLbh3EWidget4.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedMaterialsymbolssquareroundedWidget6.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedIonticketoutlineWidget.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedDolnabelkamenuWidget5.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedHenrykMikoajGreckiTrzytacenaorkiestrop34Widget.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedMaterialsymbolssquareroundedWidget3.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedBytesizesettingsWidget23.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedBackArrowWidget6.dart';
import 'package:flutterapp/slaskieapp/generatedwidok1gowydarzeniawidget/generated/GeneratedClaritydatelineWidget1.dart';

/* Frame Widok 1-go wydarzenia
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidok1gowydarzeniaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1032.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 1032.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 10.0,
                              right: null,
                              bottom: null,
                              width: 346.0,
                              height: 16.0,
                              child: GeneratedBrowserBariOSChromeWidget8(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 93.0,
                              right: null,
                              bottom: null,
                              width: 361.0,
                              height: 219.0,
                              child: GeneratedUnsplashw3dclmLbh3EWidget4(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 312.0,
                              right: null,
                              bottom: null,
                              width: 362.0,
                              height: 137.0,
                              child: GeneratedReviewWidget5(),
                            ),
                            Positioned(
                              left: -2.0,
                              top: 723.0,
                              right: null,
                              bottom: null,
                              width: 362.0,
                              height: 309.0,
                              child: GeneratedReviewWidget6(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 387.0,
                              right: null,
                              bottom: null,
                              width: 288.0,
                              height: 39.0,
                              child:
                                  GeneratedBiletnormalny45zBiletulgowy32zWidget(),
                            ),
                            Positioned(
                              left: 322.0,
                              top: 52.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedBytesizesettingsWidget23(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 329.0,
                              right: null,
                              bottom: null,
                              width: 18.0,
                              height: 18.0,
                              child: GeneratedClaritydatelineWidget1(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 329.0,
                              right: null,
                              bottom: null,
                              width: 288.0,
                              height: 20.0,
                              child: Generated2grudnia20221900Widget(),
                            ),
                            Positioned(
                              left: 14.0,
                              top: 473.0,
                              right: null,
                              bottom: null,
                              width: 291.0,
                              height: 23.0,
                              child: GeneratedWykonawcyWidget(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 361.0,
                              right: null,
                              bottom: null,
                              width: 288.0,
                              height: 20.0,
                              child:
                                  GeneratedSalaKoncertowaFilharmonialskaWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 254.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 58.0,
                              child: GeneratedGuidesWidget21(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 359.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child:
                                  GeneratedMaterialsymbolslocationonoutlineWidget(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 396.0,
                              right: null,
                              bottom: null,
                              width: 18.0,
                              height: 18.0,
                              child: GeneratedIonticketoutlineWidget(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 389.0,
                              right: null,
                              bottom: null,
                              width: 136.0,
                              height: 31.0,
                              child: GeneratedFrame40Widget8(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 499.0,
                              right: null,
                              bottom: null,
                              width: 288.0,
                              height: 20.0,
                              child: GeneratedRomanWidaszekklarnetWidget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 504.0,
                              right: null,
                              bottom: null,
                              width: 8.0,
                              height: 8.0,
                              child:
                                  GeneratedMaterialsymbolssquareroundedWidget(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 517.0,
                              right: null,
                              bottom: null,
                              width: 288.0,
                              height: 20.0,
                              child: GeneratedYaroslavShemetdyrygentWidget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 522.0,
                              right: null,
                              bottom: null,
                              width: 8.0,
                              height: 8.0,
                              child:
                                  GeneratedMaterialsymbolssquareroundedWidget1(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 517.0,
                              right: null,
                              bottom: null,
                              width: 288.0,
                              height: 20.0,
                              child: GeneratedYaroslavShemetdyrygentWidget1(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 522.0,
                              right: null,
                              bottom: null,
                              width: 8.0,
                              height: 8.0,
                              child:
                                  GeneratedMaterialsymbolssquareroundedWidget2(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 535.0,
                              right: null,
                              bottom: null,
                              width: 288.0,
                              height: 20.0,
                              child:
                                  GeneratedOrkiestraSymfonicznaFilharmoniilskiejWidget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 540.0,
                              right: null,
                              bottom: null,
                              width: 8.0,
                              height: 8.0,
                              child:
                                  GeneratedMaterialsymbolssquareroundedWidget3(),
                            ),
                            Positioned(
                              left: 14.0,
                              top: 571.0,
                              right: null,
                              bottom: null,
                              width: 291.0,
                              height: 23.0,
                              child: GeneratedProgramWidget(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 597.0,
                              right: null,
                              bottom: null,
                              width: 306.0,
                              height: 36.0,
                              child:
                                  GeneratedHenrykMikoajGreckiTrzytacenaorkiestrop34Widget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 602.0,
                              right: null,
                              bottom: null,
                              width: 8.0,
                              height: 8.0,
                              child:
                                  GeneratedMaterialsymbolssquareroundedWidget4(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 631.0,
                              right: null,
                              bottom: null,
                              width: 306.0,
                              height: 36.0,
                              child:
                                  GeneratedMarcelChyrzyskiUkiyoeNo5Koncertnaklarnetiorkiestrsymfon(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 749.0,
                              right: null,
                              bottom: null,
                              width: 323.0,
                              height: 208.0,
                              child:
                                  Generated2grudniaOrkiestraSymfonicznaFilharmoniilskiejzaprosinan(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 636.0,
                              right: null,
                              bottom: null,
                              width: 8.0,
                              height: 8.0,
                              child:
                                  GeneratedMaterialsymbolssquareroundedWidget5(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 665.0,
                              right: null,
                              bottom: null,
                              width: 306.0,
                              height: 36.0,
                              child:
                                  GeneratedHectorBerliozSymfoniafantastycznacmollop14Widget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 670.0,
                              right: null,
                              bottom: null,
                              width: 8.0,
                              height: 8.0,
                              child:
                                  GeneratedMaterialsymbolssquareroundedWidget6(),
                            ),
                            Positioned(
                              left: 14.0,
                              top: 49.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedBackArrowWidget6(),
                            ),
                            Positioned(
                              left: 139.0,
                              top: 43.0,
                              right: null,
                              bottom: null,
                              width: 85.17073059082031,
                              height: 36.0,
                              child: GeneratedZrzutekranu2022123o17242Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 725.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 77.0,
                              child: GeneratedDolnabelkamenuWidget5(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
