import 'package:flutter/material.dart';
import 'package:flutterapp/slaskieapp/generatedustawieniawidget1/generated/GeneratedBytesizesettingsWidget5.dart';
import 'package:flutterapp/slaskieapp/generatedustawieniawidget1/generated/GeneratedPowiadomieniaWidget.dart';
import 'package:flutterapp/slaskieapp/generatedustawieniawidget1/generated/GeneratedUstawieniaWidget2.dart';
import 'package:flutterapp/slaskieapp/generatedustawieniawidget1/generated/GeneratedFrame11Widget2.dart';
import 'package:flutterapp/slaskieapp/generatedustawieniawidget1/generated/GeneratedFrame16Widget.dart';
import 'package:flutterapp/slaskieapp/generatedustawieniawidget1/generated/GeneratedBrowserBariOSChromeWidget3.dart';
import 'package:flutterapp/slaskieapp/generatedustawieniawidget1/generated/GeneratedPersonalizacjaWidget.dart';
import 'package:flutterapp/slaskieapp/generatedustawieniawidget1/generated/GeneratedAktualizacjatreciWidget.dart';
import 'package:flutterapp/slaskieapp/generatedustawieniawidget1/generated/GeneratedFrame17Widget.dart';
import 'package:flutterapp/slaskieapp/generatedustawieniawidget1/generated/GeneratedFrame10Widget2.dart';
import 'package:flutterapp/slaskieapp/generatedustawieniawidget1/generated/GeneratedDolnabelkamenuWidget.dart';
import 'package:flutterapp/slaskieapp/generatedustawieniawidget1/generated/GeneratedFrame15Widget.dart';
import 'package:flutterapp/slaskieapp/generatedustawieniawidget1/generated/GeneratedFrame12Widget1.dart';
import 'package:flutterapp/slaskieapp/generatedustawieniawidget1/generated/GeneratedFrame13Widget10.dart';
import 'package:flutterapp/slaskieapp/generatedustawieniawidget1/generated/GeneratedInformacjeWidget.dart';
import 'package:flutterapp/slaskieapp/generatedustawieniawidget1/generated/GeneratedBackArrowWidget1.dart';
import 'package:flutterapp/slaskieapp/generatedustawieniawidget1/generated/GeneratedFrame14Widget10.dart';

/* Frame Ustawienia
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUstawieniaWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 802.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 13.0,
                top: 131.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 44.0,
                child: GeneratedFrame10Widget2(),
              ),
              Positioned(
                left: 22.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 2.0,
                child: GeneratedAktualizacjatreciWidget(),
              ),
              Positioned(
                left: 13.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 44.0,
                child: GeneratedFrame14Widget10(),
              ),
              Positioned(
                left: 13.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 44.0,
                child: GeneratedFrame16Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 532.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 44.0,
                child: GeneratedFrame17Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 412.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 44.0,
                child: GeneratedFrame15Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 5.0,
                child: GeneratedInformacjeWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 5.0,
                child: GeneratedPersonalizacjaWidget(),
              ),
              Positioned(
                left: 13.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 39.0,
                child: GeneratedFrame11Widget2(),
              ),
              Positioned(
                left: 13.0,
                top: 267.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 39.0,
                child: GeneratedFrame12Widget1(),
              ),
              Positioned(
                left: 13.0,
                top: 322.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 39.0,
                child: GeneratedFrame13Widget10(),
              ),
              Positioned(
                left: 21.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 5.0,
                child: GeneratedPowiadomieniaWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 49.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedBackArrowWidget1(),
              ),
              Positioned(
                left: 322.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBytesizesettingsWidget5(),
              ),
              Positioned(
                left: 122.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 33.0,
                child: GeneratedUstawieniaWidget2(),
              ),
              Positioned(
                left: 7.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 16.0,
                child: GeneratedBrowserBariOSChromeWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 725.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 77.0,
                child: GeneratedDolnabelkamenuWidget(),
              )
            ]),
      ),
    ));
  }
}
