import 'package:flutter/material.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnocilistawidget/generated/GeneratedBrowserBariOSChromeWidget7.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnocilistawidget/generated/GeneratedAktualnociWidget2.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnocilistawidget/generated/GeneratedDolnabelkamenuWidget4.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnocilistawidget/generated/GeneratedFrame8Widget3.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnocilistawidget/generated/GeneratedBytesizesettingsWidget20.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnocilistawidget/generated/GeneratedFrame9Widget3.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnocilistawidget/generated/GeneratedBackArrowWidget5.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnocilistawidget/generated/GeneratedAnkietyWidget5.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnocilistawidget/generated/GeneratedGuidesWidget15.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnocilistawidget/generated/GeneratedFrame39Widget5.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnocilistawidget/generated/Generated26wynikwWidget.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnocilistawidget/generated/GeneratedGuidesWidget20.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnocilistawidget/generated/GeneratedGuidesWidget16.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnocilistawidget/generated/GeneratedFrame10Widget3.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnocilistawidget/generated/GeneratedGuidesWidget17.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnocilistawidget/generated/GeneratedGuidesWidget14.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnocilistawidget/generated/GeneratedFrame11Widget3.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnocilistawidget/generated/GeneratedGuidesWidget19.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnocilistawidget/generated/GeneratedGuidesWidget18.dart';
import 'package:flutterapp/slaskieapp/generatedaktualnocilistawidget/generated/GeneratedGuidesWidget13.dart';

/* Frame Aktualności lista
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAktualnocilistaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1150.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 1150.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 10.0,
                              right: null,
                              bottom: null,
                              width: 346.0,
                              height: 16.0,
                              child: GeneratedBrowserBariOSChromeWidget7(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 88.0,
                              right: null,
                              bottom: null,
                              width: 333.0,
                              height: 39.0,
                              child: GeneratedFrame8Widget3(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 143.0,
                              right: null,
                              bottom: null,
                              width: 142.0,
                              height: 31.0,
                              child: GeneratedFrame9Widget3(),
                            ),
                            Positioned(
                              left: 160.0,
                              top: 143.0,
                              right: null,
                              bottom: null,
                              width: 123.0,
                              height: 31.0,
                              child: GeneratedFrame10Widget3(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 689.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 30.0,
                              child: GeneratedAnkietyWidget5(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 245.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 192.0,
                              child: GeneratedGuidesWidget13(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 454.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 192.0,
                              child: GeneratedGuidesWidget14(),
                            ),
                            Positioned(
                              left: 187.0,
                              top: 245.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 192.0,
                              child: GeneratedGuidesWidget15(),
                            ),
                            Positioned(
                              left: 186.0,
                              top: 196.0,
                              right: null,
                              bottom: null,
                              width: 159.0,
                              height: 25.0,
                              child: GeneratedFrame39Widget5(),
                            ),
                            Positioned(
                              left: 187.0,
                              top: 454.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 192.0,
                              child: GeneratedGuidesWidget16(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 663.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 192.0,
                              child: GeneratedGuidesWidget17(),
                            ),
                            Positioned(
                              left: 187.0,
                              top: 663.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 192.0,
                              child: GeneratedGuidesWidget18(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 872.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 192.0,
                              child: GeneratedGuidesWidget19(),
                            ),
                            Positioned(
                              left: 187.0,
                              top: 872.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 192.0,
                              child: GeneratedGuidesWidget20(),
                            ),
                            Positioned(
                              left: 288.0,
                              top: 143.0,
                              right: null,
                              bottom: null,
                              width: 142.0,
                              height: 31.0,
                              child: GeneratedFrame11Widget3(),
                            ),
                            Positioned(
                              left: 14.0,
                              top: 49.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedBackArrowWidget5(),
                            ),
                            Positioned(
                              left: 322.0,
                              top: 52.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedBytesizesettingsWidget20(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 199.0,
                              right: null,
                              bottom: null,
                              width: 83.0,
                              height: 21.0,
                              child: Generated26wynikwWidget(),
                            ),
                            Positioned(
                              left: 118.0,
                              top: 50.0,
                              right: null,
                              bottom: null,
                              width: 128.0,
                              height: 33.0,
                              child: GeneratedAktualnociWidget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 725.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 77.0,
                              child: GeneratedDolnabelkamenuWidget4(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
