import 'package:flutter/material.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzeniazfiltramipodstawowymiwidget/generated/GeneratedBytesizesettingsWidget.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzeniazfiltramipodstawowymiwidget/generated/GeneratedReviewWidget.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzeniazfiltramipodstawowymiwidget/generated/GeneratedRectangle1Widget3.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzeniazfiltramipodstawowymiwidget/generated/GeneratedComponent3Widget.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzeniazfiltramipodstawowymiwidget/generated/GeneratedBrowserBariOSChromeWidget.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzeniazfiltramipodstawowymiwidget/generated/GeneratedFrame45Widget1.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzeniazfiltramipodstawowymiwidget/generated/GeneratedFrame12Widget.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzeniazfiltramipodstawowymiwidget/generated/GeneratedFrame41Widget1.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzeniazfiltramipodstawowymiwidget/generated/GeneratedComponent2Widget.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzeniazfiltramipodstawowymiwidget/generated/GeneratedFrame44Widget.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzeniazfiltramipodstawowymiwidget/generated/GeneratedObraz3Widget.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzeniazfiltramipodstawowymiwidget/generated/Generated16wynikwWidget.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzeniazfiltramipodstawowymiwidget/generated/GeneratedFrame40Widget1.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzeniazfiltramipodstawowymiwidget/generated/GeneratedFrame42Widget1.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzeniazfiltramipodstawowymiwidget/generated/GeneratedPopularItineraryWidget.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzeniazfiltramipodstawowymiwidget/generated/GeneratedBackArrowWidget.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzeniazfiltramipodstawowymiwidget/generated/GeneratedComponent4Widget.dart';
import 'package:flutterapp/slaskieapp/generatedwydarzeniazfiltramipodstawowymiwidget/generated/GeneratedFrame8Widget.dart';

/* Frame Wydarzenia z filtrami podstawowymi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWydarzeniazfiltramipodstawowymiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: LayoutBuilder(
            builder: (BuildContext context, BoxConstraints constraints) {
          return SingleChildScrollView(
            scrollDirection: Axis.vertical,
            child: Container(
                height: 1403.0000305175781,
                child: Stack(children: [
                  Container(
                      width: constraints.maxWidth,
                      child: Container(
                        width: 360.0,
                        height: 1214.0,
                        child: Stack(
                            fit: StackFit.expand,
                            alignment: Alignment.center,
                            overflow: Overflow.visible,
                            children: [
                              ClipRRect(
                                borderRadius: BorderRadius.zero,
                                child: Container(
                                  color: Color.fromARGB(255, 255, 255, 255),
                                ),
                              ),
                              Positioned(
                                left: 7.0,
                                top: 10.0,
                                right: null,
                                bottom: null,
                                width: 346.0,
                                height: 16.0,
                                child: GeneratedBrowserBariOSChromeWidget(),
                              ),
                              Positioned(
                                left: 13.0,
                                top: 88.0,
                                right: null,
                                bottom: null,
                                width: 333.0,
                                height: 39.0,
                                child: GeneratedFrame8Widget(),
                              ),
                              Positioned(
                                left: 17.0,
                                top: 491.0,
                                right: null,
                                bottom: null,
                                width: 158.0,
                                height: 214.0,
                                child: GeneratedPopularItineraryWidget(),
                              ),
                              Positioned(
                                left: 183.0,
                                top: 491.0,
                                right: null,
                                bottom: null,
                                width: 158.0,
                                height: 214.0,
                                child: GeneratedComponent2Widget(),
                              ),
                              Positioned(
                                left: -7.0,
                                top: 188.0,
                                right: null,
                                bottom: null,
                                width: 367.0,
                                height: 274.0,
                                child: GeneratedReviewWidget(),
                              ),
                              Positioned(
                                left: 13.0,
                                top: 218.0,
                                right: null,
                                bottom: null,
                                width: 333.0,
                                height: 41.0,
                                child: GeneratedFrame44Widget(),
                              ),
                              Positioned(
                                left: 13.0,
                                top: 284.0,
                                right: null,
                                bottom: null,
                                width: 333.0,
                                height: 41.0,
                                child: GeneratedFrame45Widget1(),
                              ),
                              Positioned(
                                left: 17.0,
                                top: 733.0,
                                right: null,
                                bottom: null,
                                width: 158.0,
                                height: 214.0,
                                child: GeneratedComponent3Widget(),
                              ),
                              Positioned(
                                left: 183.0,
                                top: 733.0,
                                right: null,
                                bottom: null,
                                width: 158.0,
                                height: 214.0,
                                child: GeneratedComponent4Widget(),
                              ),
                              Positioned(
                                left: 360.0,
                                top: 1214.0,
                                right: null,
                                bottom: null,
                                width: 359.9999694824219,
                                height: 189.00003051757812,
                                child: GeneratedRectangle1Widget3(),
                              ),
                              Positioned(
                                left: 17.0,
                                top: 49.0,
                                right: null,
                                bottom: null,
                                width: 30.0,
                                height: 30.0,
                                child: GeneratedBackArrowWidget(),
                              ),
                              Positioned(
                                left: 322.0,
                                top: 52.0,
                                right: null,
                                bottom: null,
                                width: 24.0,
                                height: 24.0,
                                child: GeneratedBytesizesettingsWidget(),
                              ),
                              Positioned(
                                left: 23.0,
                                top: 145.0,
                                right: null,
                                bottom: null,
                                width: 85.0,
                                height: 22.0,
                                child: Generated16wynikwWidget(),
                              ),
                              Positioned(
                                left: 72.0,
                                top: 44.0,
                                right: null,
                                bottom: null,
                                width: 221.6666717529297,
                                height: 40.0,
                                child: GeneratedObraz3Widget(),
                              ),
                              Positioned(
                                left: 198.0,
                                top: 140.0,
                                right: null,
                                bottom: null,
                                width: 147.0,
                                height: 31.0,
                                child: GeneratedFrame12Widget(),
                              ),
                              Positioned(
                                left: 13.0,
                                top: 400.0,
                                right: null,
                                bottom: null,
                                width: 134.0,
                                height: 31.0,
                                child: GeneratedFrame42Widget1(),
                              ),
                              Positioned(
                                left: 13.0,
                                top: 350.0,
                                right: null,
                                bottom: null,
                                width: 149.0,
                                height: 25.0,
                                child: GeneratedFrame40Widget1(),
                              ),
                              Positioned(
                                left: 203.0,
                                top: 350.0,
                                right: null,
                                bottom: null,
                                width: 143.0,
                                height: 25.0,
                                child: GeneratedFrame41Widget1(),
                              )
                            ]),
                      ))
                ])),
          );
        }),
      ),
    ));
  }
}
