import 'package:flutter/material.dart';

/* UndefinedNode Popular Itinerary
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPopularItineraryWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
