import 'package:flutter/material.dart';
import 'package:flutterapp/slaskieapp/generatedguidedetailswidget/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/slaskieapp/generatedguidedetailswidget/generated/GeneratedGroup7Widget7.dart';
import 'package:flutterapp/slaskieapp/generatedguidedetailswidget/generated/GeneratedNotificationWidget1.dart';
import 'package:flutterapp/slaskieapp/generatedguidedetailswidget/generated/Generated\$30PerDayWidget.dart';
import 'package:flutterapp/slaskieapp/generatedguidedetailswidget/generated/GeneratedLocationWidget.dart';
import 'package:flutterapp/slaskieapp/generatedguidedetailswidget/generated/GeneratedGroup41Widget1.dart';
import 'package:flutterapp/slaskieapp/generatedguidedetailswidget/generated/GeneratedNativeGuideWidget3.dart';
import 'package:flutterapp/slaskieapp/generatedguidedetailswidget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/slaskieapp/generatedguidedetailswidget/generated/GeneratedGuideNameWidget.dart';
import 'package:flutterapp/slaskieapp/generatedguidedetailswidget/generated/GeneratedGroup34Widget.dart';
import 'package:flutterapp/slaskieapp/generatedguidedetailswidget/generated/GeneratedGroup1Widget1.dart';
import 'package:flutterapp/slaskieapp/generatedguidedetailswidget/generated/GeneratedRectangle7Widget1.dart';
import 'package:flutterapp/slaskieapp/generatedguidedetailswidget/generated/GeneratedGroup26Widget.dart';
import 'package:flutterapp/slaskieapp/generatedguidedetailswidget/generated/GeneratedGroup30Widget.dart';

/* Frame Guide Details
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGuideDetailsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -21.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 459.0,
                height: 92.0,
                child: GeneratedRectangle7Widget1(),
              ),
              Positioned(
                left: 337.0,
                top: 18.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 36.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 27.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 19.0,
                child: GeneratedGroup1Widget1(),
              ),
              Positioned(
                left: 33.0,
                top: 77.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 177.0,
                child: GeneratedGroup7Widget7(),
              ),
              Positioned(
                left: 334.0,
                top: 22.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 28.0,
                child: GeneratedNotificationWidget1(),
              ),
              Positioned(
                left: 33.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 28.0,
                child: GeneratedGuideNameWidget(),
              ),
              Positioned(
                left: 33.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 21.0,
                child: GeneratedLocationWidget(),
              ),
              Positioned(
                left: 294.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 28.0,
                child: Generated$30PerDayWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 341.0,
                height: 61.0,
                child: GeneratedGroup34Widget(),
              ),
              Positioned(
                left: 174.0,
                top: 262.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 10.0,
                child: GeneratedGroup26Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 341.0,
                height: 247.0,
                child: GeneratedGroup30Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 744.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 68.0,
                child: GeneratedRectangle6Widget1(),
              ),
              Positioned(
                left: 145.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 29.0,
                child: GeneratedNativeGuideWidget3(),
              ),
              Positioned(
                left: 36.0,
                top: 759.0,
                right: null,
                bottom: null,
                width: 342.69000244140625,
                height: 38.0,
                child: GeneratedGroup41Widget1(),
              )
            ]),
      ),
    ));
  }
}
